[2025-04-08T03:18:14.995+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T03:18:15.072+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Paint___Paint_Supplies_7 manual__2025-04-08T03:17:37.800589+00:00 [queued]>
[2025-04-08T03:18:15.209+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Paint___Paint_Supplies_7 manual__2025-04-08T03:17:37.800589+00:00 [queued]>
[2025-04-08T03:18:15.210+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T03:18:15.282+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_Paint___Paint_Supplies_7> on 2025-04-08 03:17:37.800589+00:00
[2025-04-08T03:18:15.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1200) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-08T03:18:15.329+0000] {standard_task_runner.py:72} INFO - Started process 1258 to run task
[2025-04-08T03:18:15.331+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_amazon_dag', 'process_Paint___Paint_Supplies_7', 'manual__2025-04-08T03:17:37.800589+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/test_crawl_list_product.py', '--cfg-path', '/tmp/tmp4vmsnj5o']
[2025-04-08T03:18:15.335+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask process_Paint___Paint_Supplies_7
[2025-04-08T03:18:15.503+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_amazon_dag.process_Paint___Paint_Supplies_7 manual__2025-04-08T03:17:37.800589+00:00 [running]> on host 13b4251b7529
[2025-04-08T03:18:20.318+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_amazon_dag' AIRFLOW_CTX_TASK_ID='process_Paint___Paint_Supplies_7' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T03:17:37.800589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T03:17:37.800589+00:00'
[2025-04-08T03:18:20.327+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T03:18:20.331+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T03:18:20.333+0000] {logging_mixin.py:190} INFO - Current task name:process_Paint___Paint_Supplies_7 state:running start_date:2025-04-08 03:18:15.075050+00:00
[2025-04-08T03:18:20.334+0000] {logging_mixin.py:190} INFO - Dag name:scrape_amazon_dag and current dag run status:running
[2025-04-08T03:18:20.341+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T03:18:20.346+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scrape_department() takes 1 positional argument but 2 were given
[2025-04-08T03:18:22.738+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-08T03:18:22.751+0000] {logging_mixin.py:190} INFO - Task start:2025-04-08 03:18:15.075050+00:00 end:2025-04-08 03:18:22.736084+00:00 duration:7.661034
[2025-04-08T03:18:22.755+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_Paint___Paint_Supplies_7> dag:<DAG: scrape_amazon_dag> dagrun:<DagRun scrape_amazon_dag @ 2025-04-08 03:17:37.800589+00:00: manual__2025-04-08T03:17:37.800589+00:00, state:running, queued_at: 2025-04-08 03:17:37.846847+00:00. externally triggered: True>
[2025-04-08T03:18:22.759+0000] {logging_mixin.py:190} INFO - Failure caused by scrape_department() takes 1 positional argument but 2 were given
[2025-04-08T03:18:22.765+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_amazon_dag, task_id=process_Paint___Paint_Supplies_7, run_id=manual__2025-04-08T03:17:37.800589+00:00, execution_date=20250408T031737, start_date=20250408T031815, end_date=20250408T031822
[2025-04-08T03:18:23.614+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T03:18:23.617+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 110 for task process_Paint___Paint_Supplies_7 (scrape_department() takes 1 positional argument but 2 were given; 1258)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scrape_department() takes 1 positional argument but 2 were given
[2025-04-08T03:18:23.725+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-08T03:18:23.759+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
