[2025-04-07T16:01:57.536+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T16:01:57.559+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:01:52.423179+00:00 [queued]>
[2025-04-07T16:01:57.578+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:01:52.423179+00:00 [queued]>
[2025-04-07T16:01:57.578+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-07T16:01:57.603+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_amazon_task> on 2025-04-07 16:01:52.423179+00:00
[2025-04-07T16:01:57.612+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1425) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T16:01:57.615+0000] {standard_task_runner.py:72} INFO - Started process 1447 to run task
[2025-04-07T16:01:57.615+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'amazon_scraping_dag', 'scrape_amazon_task', 'manual__2025-04-07T16:01:52.423179+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/another_another_test.py', '--cfg-path', '/tmp/tmptwm4xakn']
[2025-04-07T16:01:57.617+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask scrape_amazon_task
[2025-04-07T16:01:57.671+0000] {task_command.py:467} INFO - Running <TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:01:52.423179+00:00 [running]> on host 729426e08441
[2025-04-07T16:01:57.802+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_scraping_dag' AIRFLOW_CTX_TASK_ID='scrape_amazon_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T16:01:52.423179+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T16:01:52.423179+00:00'
[2025-04-07T16:01:57.804+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T16:01:57.805+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T16:01:57.805+0000] {logging_mixin.py:190} INFO - Current task name:scrape_amazon_task state:running start_date:2025-04-07 16:01:57.560269+00:00
[2025-04-07T16:01:57.806+0000] {logging_mixin.py:190} INFO - Dag name:amazon_scraping_dag and current dag run status:running
[2025-04-07T16:01:57.806+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-07T16:01:57.818+0000] {another_another_test.py:285} INFO - Processing 1/15: Automotive/Car Care - https://www.amazon.com/s?bbn=2562090011&rh=i%3Aspecialty-aps%2Cn%3A2562090011%2Cn%3A%2115690151%2Cn%3A15718271&s=date-desc-rank&ref_=nav_em__nav_desktop_sa_intl_car_care_0_2_10_2
[2025-04-07T16:01:57.876+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-04-07T16:01:57.902+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:01:58.056+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-04-07T16:01:58.204+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-04-07T16:01:58.953+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:01:59.298+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:01:59.470+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-04-07T16:01:59.494+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 288, in main
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 51, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/another_another_test.py", line 68, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-07T16:01:59.555+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-07T16:01:59.556+0000] {logging_mixin.py:190} INFO - Task start:2025-04-07 16:01:57.560269+00:00 end:2025-04-07 16:01:59.555341+00:00 duration:1.995072
[2025-04-07T16:01:59.556+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_amazon_task> dag:<DAG: amazon_scraping_dag> dagrun:<DagRun amazon_scraping_dag @ 2025-04-07 16:01:52.423179+00:00: manual__2025-04-07T16:01:52.423179+00:00, state:running, queued_at: 2025-04-07 16:01:52.441624+00:00. externally triggered: True>
[2025-04-07T16:01:59.557+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-04-07T16:01:59.557+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_scraping_dag, task_id=scrape_amazon_task, run_id=manual__2025-04-07T16:01:52.423179+00:00, execution_date=20250407T160152, start_date=20250407T160157, end_date=20250407T160159
[2025-04-07T16:01:59.687+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-07T16:01:59.688+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 62 for task scrape_amazon_task (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
; 1447)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 288, in main
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 51, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/another_another_test.py", line 68, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-07T16:01:59.725+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-07T16:01:59.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
