[2025-04-07T16:27:10.260+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T16:27:10.279+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:21:55.474538+00:00 [queued]>
[2025-04-07T16:27:10.289+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:21:55.474538+00:00 [queued]>
[2025-04-07T16:27:10.289+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-07T16:27:10.310+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_amazon_task> on 2025-04-07 16:21:55.474538+00:00
[2025-04-07T16:27:10.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T16:27:10.320+0000] {standard_task_runner.py:72} INFO - Started process 239 to run task
[2025-04-07T16:27:10.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'amazon_scraping_dag', 'scrape_amazon_task', 'manual__2025-04-07T16:21:55.474538+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/another_another_test.py', '--cfg-path', '/tmp/tmphm9d3lph']
[2025-04-07T16:27:10.323+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask scrape_amazon_task
[2025-04-07T16:27:10.387+0000] {task_command.py:467} INFO - Running <TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:21:55.474538+00:00 [running]> on host cde58372197d
[2025-04-07T16:27:10.502+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_scraping_dag' AIRFLOW_CTX_TASK_ID='scrape_amazon_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T16:21:55.474538+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T16:21:55.474538+00:00'
[2025-04-07T16:27:10.504+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T16:27:10.504+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T16:27:10.505+0000] {logging_mixin.py:190} INFO - Current task name:scrape_amazon_task state:running start_date:2025-04-07 16:27:10.280348+00:00
[2025-04-07T16:27:10.505+0000] {logging_mixin.py:190} INFO - Dag name:amazon_scraping_dag and current dag run status:running
[2025-04-07T16:27:10.506+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T16:27:10.519+0000] {another_another_test.py:285} INFO - Processing 1/15: Automotive/Car Care - https://www.amazon.com/s?bbn=2562090011&rh=i%3Aspecialty-aps%2Cn%3A2562090011%2Cn%3A%2115690151%2Cn%3A15718271&s=date-desc-rank&ref_=nav_em__nav_desktop_sa_intl_car_care_0_2_10_2
[2025-04-07T16:27:10.570+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-04-07T16:27:10.592+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:27:10.893+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-04-07T16:27:11.044+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-04-07T16:27:11.621+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:27:11.896+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:27:12.111+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-04-07T16:27:12.126+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 288, in main
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 51, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/another_another_test.py", line 68, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-07T16:27:12.141+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-07T16:27:12.142+0000] {logging_mixin.py:190} INFO - Task start:2025-04-07 16:27:10.280348+00:00 end:2025-04-07 16:27:12.141141+00:00 duration:1.860793
[2025-04-07T16:27:12.143+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_amazon_task> dag:<DAG: amazon_scraping_dag> dagrun:<DagRun amazon_scraping_dag @ 2025-04-07 16:21:55.474538+00:00: manual__2025-04-07T16:21:55.474538+00:00, state:running, queued_at: 2025-04-07 16:21:55.514170+00:00. externally triggered: True>
[2025-04-07T16:27:12.143+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-04-07T16:27:12.144+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=amazon_scraping_dag, task_id=scrape_amazon_task, run_id=manual__2025-04-07T16:21:55.474538+00:00, execution_date=20250407T162155, start_date=20250407T162710, end_date=20250407T162712
[2025-04-07T16:27:12.398+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T16:27:12.399+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task scrape_amazon_task (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
; 239)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 288, in main
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 51, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/another_another_test.py", line 68, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-07T16:27:12.424+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-07T16:27:12.442+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T16:27:12.452+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
